Add files
folkwiz/new pull request #2
Opened 2022-06-15 11:15 UTC by folkwiz

2022-06-15 15:55 UTC, darkhorse2407 commented
Измени что-то внутри файлов которые уже в проекте

2022-06-15 17:14 UTC, darkhorse2407 requested changes
поменяй что-то в уже присутствующих файлах

2022-06-16 06:43 UTC, folkwiz commented
я добавила в папку work картинку и удалила текстовый документ. подойдёт?

2022-06-17 14:36 UTC, darkhorse2407 approved these changes
В целом сойдёт, можно мержить

2022-06-21 07:04 UTC, merged